### ISSUE TITLE
Off by one in neovim for both diagnostic and row

### ISSUE THREAD

**Issue by Seamooo** [Seamooo/ruffd#19]
After merging https://github.com/Seamooo/ruffd/pull/17
it appears that the zero index and 1-index adjustment has been swapped, ending up with being off by +1 for row index and by -1 for column index
![image](https://user-images.githubusercontent.com/48548685/198934100-07ee5bd4-a161-4060-b1b7-e31d6e1aae2b.png)
![image](https://user-images.githubusercontent.com/48548685/198934141-6c218ec7-09bc-4e76-9f47-9cfaf0835b00.png)

To close this issue a relevant test should be submitted along with the fix

**Comment by Seamooo** [comment]
@charliermarsh just confirming this is also the case with the vscode extension you're developing

**Comment by charliermarsh** [comment]
Oops, my mistake! I did test this with the VS Code extension, but I must’ve been using a stale version or something.
