### ISSUE TITLE
Implement code action provider

### ISSUE THREAD

**Issue by Seamooo** [Seamooo/ruffd#3]
This issue will be blocked while there's no public access to the fixer api for ruff, so for now is used as a placeholder for when it becomes possible.

**Comment by charliermarsh** [comment]
@Seamooo - What can I do to enable this?

**Comment by Seamooo** [comment]
@charliermarsh Ideally the public API "check" would expose the Checks rather than the messages such that the optional "Fix" type is available. Fix has exactly the information required to facilitate the request behaviour
